notes = {
    "A": 220.000000,
    "A#": 233.080000,
    "Ab": 207.650000,
    "B": 246.940000,
    "Bb": 233.080000,
    "C": 261.625000,
    "C#": 277.185000,
    "D": 293.665000,
    "D#": 311.125000,
    "Db": 277.185000,
    "E": 329.625000,
    "Eb": 311.125000,
    "F": 349.230000,
    "F#": 369.995000,
    "G": 391.995000,
    "G#": 415.305000,
    "Gb": 369.995000,
}

intervals = {'unison': [1, 1],
             'minor second': [15, 16],
             'major second': [8, 9],
             'minor third': [5, 6],
             'major third': [4, 5],
             'fourth': [3, 4],
             'tritone': [32, 45],
             'diminished fifth': [36, 25],
             'fifth': [2, 3],
             'minor sixth': [5, 8],
             'major sixth': [3, 5],
             'minor seventh': [5, 9],
             'major seventh': [8, 15],
             'octave': [1, 2],
             'major ninth': [9, 4]}

chords = {'madd9': ['minor third', 'fifth', 'major ninth'],
          'dim': ['minor third', 'diminished fifth'],
          'dim7': ['minor third', 'minor seventh'],
          'aug': ['major third', 'minor sixth'],
          'M7b5': ['major third', 'minor seventh', 'diminished fifth'],
          'm7': ['minor third', 'fifth', 'minor seventh'],
          'm6': ['minor third', 'fifth', 'major sixth'],
          'm': ['minor third', 'fifth'],
          'sus4': ['major third', 'fourth', 'fifth'],
          'add9': ['major third', 'fifth', 'major ninth'],
          'M9': ['major third', 'fifth', 'major ninth'],
          'Maj9': ['major third', 'fifth', 'major seventh', 'major ninth'],
          'sus2': ['major second', 'fifth'],
          'M6': ['major third', 'fifth', 'major sixth'],
          'M7': ['major third', 'fifth', 'minor seventh'],
          'Maj7': ['major third', 'fifth', 'major seventh'],
          'M': ['major third', 'fifth']}

basic_emotichords = {
    'creepy': ['madd9', 'dim'],
    'ominous': ['dim7', 'aug'],
    'fear': ['M7b5', 'm'],
    'apprehensive': ['m', 'Maj7'],
    'restless': ['aug', 'M7'],
    'moody': ['M', 'dim7'],
    'melancholy': ['add9', 'm'],
    'contemplative': ['m', 'add9'],
    'optimistic': ['Maj7', 'M6'],
    'delightful': ['add9', 'm6'],
    'funky': ['m6', 'M7'],
    'romantic': ['Maj7', 'add9'],
    'cheerful': ['M', 'M9']}

advanced_emotichords = {
    'admiration': ['add9', 'M7b5'],
    'amusement': ['M', 'M7'],
    'anger': ['aug', 'dim7'],
    'annoyance': ['M9', 'M7b5'],
    'approval': ['M7', 'M9'],
    'caring': ['Maj7', 'M'],
    'confusion': ['sus4', 'aug'],
    'curiosity': ['M6', 'Msus2'],
    'desire': ['sus2', 'M'],
    'disappointment': ['M9', 'min6'],
    'disapproval': ['M7b5', 'madd9'],
    'disgust': ['madd9', 'dim'],
    'embarrassment': ['dim7', 'aug'],
    'excitement': ['m6', 'M9'],
    'fear': ['M7b5', 'm'],
    'gratitude': ['add9', 'Maj9'],
    'grief': ['M', 'dim'],
    'joy': ['M', 'M9'],
    'love': ['Maj7', 'add9'],
    'nervousness': ['sus2', 'dim'],
    'optimism': ['Maj7', 'M6'],
    'pride': ['sus4', 'Maj7'],
    'realization': ['m6', 'Maj7'],
    'relief': ['M7', 'm'],
    'remorse': ['dim7', 'm6'],
    'sadness': ['add9', 'madd9'],
    'surprise': ['M9', 'm'],
    'neutral': ['sus2', 'sus2']
}
